dist: xenial

language: python 
python: 
- "3.6"

install: 
- pip install -r requirements.txt
- pip install codacy-coverage

script: 
- cd innosoft_diplomas
- python tests.py
- coverage xml
- python-codacy-coverage -r coverage.xml

