dist: xenial

language: python 
python: 
- "3.6"

before_install:
  - "pip install -U pip"
  - "export PYTHONPATH=$PYTHONPATH:$(pwd)"

install: 
- pip install -r requirements.txt
- pip install coverage
- pip install codacy-coverage

script: 
- python -m unittest innosoft_diplomas/tests.py
- coverage run --branch --source=. ./tests.py --with-xunit
- coverage xml
- python-codacy-coverage -r coverage.xml


