dist: xenial

language: python 
python: 
- "3.6"

before_install:
  - "pip install -U pip"
  - "export PYTHONPATH=$PYTHONPATH:$(pwd)"
  
install: 
- pip install -r requirements.txt
- pip install codacy-coverage

script: 
- cd innosoft_diplomas
- python tests.py
- coverage xml
- python-codacy-coverage -r coverage.xml

