dist: xenial

language: python 
python: 
- "3.6"

install: 
- pip install -r requirements.txt
- pip install codacy-coverage

script: 
- cd InnosoftDiploma
- python test.py
-COMANDO COVERAGE RUN COMPLETAR
- coverage xml
- python-codacy-coverage -r coverage.xml

